GET http://localhost:8080/users

###

GET http://localhost:8080/users/645a771ae85d24fa346dc665


###

POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Hello",
    "email": "christoffer.jadermark@gmail.com",
    "password": "123456"
}

###

DELETE http://localhost:8080/users/645ce7b1ec4b1cb0255e0d2a